log4r_config:

  loggers:
    - name      : production
      level     : ERROR
      trace     : 'false'
      outputters :
        - datefile_production

    - name      : mirror
      trace     : 'false'
      outputters :
        - datefile_debug
        - datefile_error


    - name      : staging
      trace     : 'false'
      outputters :
        - datefile_debug
        - datefile_error

    - name      : develop
      trace     : 'false'
      outputters :
        - datefile_debug
        - datefile_error

  outputters:
    - type: DateFileOutputter
      name: datefile_production
      dirname: "log"
      filename: "production.log" # notice the file extension is needed!
      formatter:
        date_pattern: '%H:%M:%S'
        pattern     : '%d %l: %m '
        type        : PatternFormatter

    - type: DateFileOutputter
      name: datefile_debug
      dirname: "log"
      level: DEBUG
      filename: "library_debug.log" # notice the file extension is needed!
      formatter:
        type        : PatternFormatter
        date_pattern: '%H:%M:%S'
        pattern     : '%d %l: %c %t %m '
    - type: DateFileOutputter
      name: datefile_error
      dirname: "log"
      level     : ERROR
      filename: "library_error.log" # notice the file extension is needed!
      formatter:
        type        : PatternFormatter
        date_pattern: '%H:%M:%S'
        pattern     : '%d %l: %m '